version: '3.9'
services:
  web_server:
    image: node:16.3.0
    profiles:
      - web_server
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: "/app"
    command: "npm run dev"
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=advanced-web.local

  redis:
    image: redis
    profiles:
      - web_server

  redis-ui:
    image: marian/rebrow
    profiles:
      - debug

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 127.0.0.1:80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx/vhost.d:/etc/nginx/vhost.d:ro
