version: '3'
services:
  web_server:
    image: node:16.3.0
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: "/app"
    command: "npm run dev"
    environment:
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=basic-web.local

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 127.0.0.1:80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
